var tradingCourse = "Extensive, essential\ncourse for beginner\ntraders. Accelerate your\nknowledge by watching\nmore than 2h+ of content\nby Head of Trading Jan\nSrajer!"
var profitTarget = "The profit you need to\n reach within the\nChallenge.Calculated\nbased on closed positions\n only."
var maxDrawDown = "All your open and\nclosed profits and losses\ncombines can't exceed this amount."
var dailyDrawDown = "The maximum daily loss,\ncalculated from your\ninitial account balance,\naccounting for both open\nand closed positions.\nresets daily."
var payouts = "How often you can\nrequest to withdraw your\nprofits."
var profitSplit = "The percentage of the\nprofits you make on your\ntrades that you can\nwithdraw as a reward."
var bonus = "If you pass the Trading\nChallenge, you will get a\n cash bonus of the\n selected amount as part\nof your first performance\nreward."
var timeLimit = "This is the limit in which\nyou must complete your\nChallenge(Pahse1 and/or\nPhase). Additionally, you\nneed to open or close at\nleast one trade every 30\ndays to keep the account\nopen."
var oneTimeFee = "The price of entry into the\nchallenege. Pass\n successfully and get it back!"
var Phase1 = "The profit you need to\n reach within Phase 1\n of the Challenge.\nCalculated based on\nclosed positions only."
var Phase2 = "The profit you need to\n reach within Phase 2\n of the Challenge.\nCalculated based on\nclosed positions only."
var maxWithdraw = "This account has a\nmaximum withdrawal\nlimit. Once you reach this\nlimit, your Binary Funded\nAccount will be closed,\nand you will need to\npurchase another\nchallenge if you wish to\ncontinue trading."
var refund = "The price of entry into the challenge. Pass successfully\n and get it back!"
export {tradingCourse, profitTarget, profitSplit, maxDrawDown, dailyDrawDown, payouts, bonus, timeLimit, oneTimeFee,Phase1, Phase2, maxWithdraw,refund};